
def get_info():
    # reading recept_info regenerated by Recept.exe everytime something moves in the office
    # and declaring some basic stuff
    f = open('C://Users/Tom/Documents/Python/Bot/Receptura/Recept/Recept/bin/Release/recept_info.txt', 'r', encoding= 'UTF-8')
    s = []
    list_of_prosecutor = []
    list_of_deputy = []
    deputy_on_duty = True
    prosecutor_on_duty = False
    s = f.read().split('\n')
    print(s)
    if s[1] == '+':
        deputy_on_duty = True
    else:
        deputy_on_duty = False
    i = 2

    # getting names into local variables form recept_info
    while s[i] != 'шеф':
        if (s[i] != '') and (s[i] != ' '):
            list_of_deputy.append(s[i])
        i += 1
    if s[i+1] == '+':
        prosecutor_on_duty = True
    else:
        prosecutor_on_duty = False
    i += 2
    while i < len(s):
        if (s[i] != '') and (s[i] != ' '):
            list_of_prosecutor.append(s[i])
        i += 1
    
    # forming final output strings for deputy and prosecutor
    deputy_result = 'Заместитель '
    prosecutor_result = 'Прокурор '
    if deputy_on_duty :
        deputy_result += 'на месте, у него'
        if len(list_of_deputy) == 0 : 
            deputy_result += ' никого'
        else :
            deputy_result += ':\n'
            for guest in list_of_deputy:
                deputy_result += guest + '\n'
    else:
        deputy_result += 'не на месте'
    
    if prosecutor_on_duty :
        prosecutor_result += 'на месте, у него'
        if len(list_of_prosecutor) == 0 : 
            prosecutor_result += ' никого'
        else :
            prosecutor_result += ':\n'
            for guest in list_of_prosecutor:
                prosecutor_result += guest + '\n'
    else:
        prosecutor_result += 'не на месте'
    
    return (deputy_result, prosecutor_result)


def main():
    message = get_info()
    print(str(message[0]))
    
if __name__ == "__main__":
    main()